apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: devopspulse
  labels:
    app: devopspulse
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: devopspulse
    tier: frontend
  ports:
    - port: 80
      targetPort: 8080
